### Register new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Ekaterina",
  "email": "ekaterina@test.com",
  "password": "password123"
}

### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "ekaterina@test.com",
  "password": "password123"
}